name: visitplusapp
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  firebase_core: ^2.30.1
  firebase_auth: ^4.19.4
  cloud_firestore: ^4.17.3
  firebase_database: ^10.5.4
  google_sign_in: ^6.2.1
  image_picker: ^1.1.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/facebook.png
    - assets/Google.webp
    - assets/linkedin.png
    - assets/doctor1.png
    - assets/doctor2.png
    - assets/profile.png
    - assets/hospital.jpeg
